env: local

app:
  env: local
  name: temp-go
  version: v0.0.1

postgres:
  type: postgres
  host: localhost
  port: 5432
  name: test-task-two
  user: demo
  password: demo
  schema: public
  maxAttempts: 5
  attemptDelay: 5s
  migrationPath: migrations/pg
